Added some cosmetics and parallel DSC build support bits

diff --git a/build-recipe-simpleimage b/build-recipe-simpleimage
--- a/build-recipe-simpleimage
+++ b/build-recipe-simpleimage
@@ -125,7 +125,12 @@ recipe_build_simpleimage() {
     rm -f $BUILD_ROOT/.build.packages
     ln -s ${TOPDIR#/} $BUILD_ROOT/.build.packages
     echo "`date -u`: recipe_build_simpleimage() finished"
-    test -d "$SRCDIR" && cd "$SRCDIR"
+    test -d "$SRCDIR" && cd "$SRCDIR" || echo "NOTE: Could not test existance of SRCDIR='$SRCDIR'"
+
+    echo
+    echo "$HOST finished \"build $RECIPEFILE\" at `date --utc`."
+    echo
+
     cleanup_and_exit 0
 }
 
